spring:
  application:
    name: "server"
  datasource:
    url: jdbc:h2:file:./database/mydb;AUTO_SERVER=TRUE;SCHEMA=PUBLIC;
    username: SA
    password: PASSWORD
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:/database/schema.sql
      data-locations: classpath:/database/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  banner:
    location: banner.txt
